# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baseTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def toggleTracker(self):
        text = self.toggleTrackerButton.text()
        if text == 'Tracking: ON':
            self.toggleTrackerButton.setText("Tracking: OFF")
        else:
            self.toggleTrackerButton.setText("Tracking: ON")

    def adjustRX(self):
        currentValue = self.RxDial.value()
        self.labelRxGain.setText(str(currentValue))

    def adjustTX(self):
        currentValue = self.TxDial.value()
        self.labelTxGain.setText(str(currentValue))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.trackerView = GraphicsLayoutWidget(self.centralwidget)
        self.trackerView.setGeometry(QtCore.QRect(20, 20, 511, 401))
        self.trackerView.setObjectName("trackerView")

        self.RxDial = QtWidgets.QDial(self.centralwidget)
        self.RxDial.setGeometry(QtCore.QRect(140, 440, 91, 81))
        self.RxDial.setObjectName("RxDial")
        self.RxDial.setValue(60)
        self.RxDial.valueChanged.connect(self.adjustRX)

        self.TxDial = QtWidgets.QDial(self.centralwidget)
        self.TxDial.setGeometry(QtCore.QRect(240, 440, 91, 81))
        self.TxDial.setObjectName("TxDial")
        self.TxDial.setValue(0)
        self.TxDial.valueChanged.connect(self.adjustTX)

        self.phaseCalibration = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.phaseCalibration.setGeometry(QtCore.QRect(350, 480, 101, 31))
        self.phaseCalibration.setMinimum(-180.0)
        self.phaseCalibration.setMaximum(180.0)
        self.phaseCalibration.setSingleStep(0.5)
        self.phaseCalibration.setObjectName("phaseCalibration")

        self.labelPhaseCal = QtWidgets.QLabel(self.centralwidget)
        self.labelPhaseCal.setGeometry(QtCore.QRect(350, 460, 121, 16))
        self.labelPhaseCal.setObjectName("labelPhaseCal")

        self.labelDial1 = QtWidgets.QLabel(self.centralwidget)
        self.labelDial1.setGeometry(QtCore.QRect(150, 430, 71, 16))
        self.labelDial1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDial1.setObjectName("labelDial1")

        self.labelDial2 = QtWidgets.QLabel(self.centralwidget)
        self.labelDial2.setGeometry(QtCore.QRect(250, 430, 71, 16))
        self.labelDial2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDial2.setObjectName("labelDial2")

        self.firstWidget = GraphicsLayoutWidget(self.centralwidget)
        self.firstWidget.setGeometry(QtCore.QRect(545, 20, 231, 201))
        self.firstWidget.setObjectName("firstWidget")

        self.secondWidget = GraphicsLayoutWidget(self.centralwidget)
        self.secondWidget.setGeometry(QtCore.QRect(545, 230, 231, 191))
        self.secondWidget.setObjectName("secondWidget")

        self.toggleTrackerButton = QtWidgets.QPushButton(self.centralwidget)
        self.toggleTrackerButton.setGeometry(QtCore.QRect(20, 440, 111, 91))
        self.toggleTrackerButton.setObjectName("toggleTrackerButton")
        self.toggleTrackerButton.clicked.connect(self.toggleTracker)

        self.labelRxGain = QtWidgets.QLabel(self.centralwidget)
        self.labelRxGain.setGeometry(QtCore.QRect(150, 520, 71, 16))
        self.labelRxGain.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRxGain.setObjectName("labelRxGain")

        self.labelTxGain = QtWidgets.QLabel(self.centralwidget)
        self.labelTxGain.setGeometry(QtCore.QRect(250, 520, 71, 16))
        self.labelTxGain.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTxGain.setObjectName("labelTxGain")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionThis_is_an_option = QtWidgets.QAction(MainWindow)
        self.actionThis_is_an_option.setObjectName("actionThis_is_an_option")
        self.actionA_second_option = QtWidgets.QAction(MainWindow)
        self.actionA_second_option.setObjectName("actionA_second_option")
        self.actionAnd_so_on = QtWidgets.QAction(MainWindow)
        self.actionAnd_so_on.setObjectName("actionAnd_so_on")
        self.menuFile.addAction(self.actionThis_is_an_option)
        self.menuFile.addAction(self.actionA_second_option)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAnd_so_on)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelPhaseCal.setText(_translate("MainWindow", "Phase Calibration"))
        self.labelDial1.setText(_translate("MainWindow", "Rx Gain"))
        self.labelDial2.setText(_translate("MainWindow", "Tx Gain"))
        self.toggleTrackerButton.setText(_translate("MainWindow", "Tracking: ON"))
        self.labelRxGain.setText(_translate("MainWindow", "60"))
        self.labelTxGain.setText(_translate("MainWindow", "0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionThis_is_an_option.setText(_translate("MainWindow", "This is an option"))
        self.actionA_second_option.setText(_translate("MainWindow", "A second option"))
        self.actionAnd_so_on.setText(_translate("MainWindow", "And so on"))
from pyqtgraph import GraphicsLayoutWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
